[package]
edition = "2021"
name = "squisher"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gltf = {features = ["KHR_lights_punctual"], version = "1.0"}
image = "0.24"
seahash = "4.1.0"

[dev-dependencies]
ktx2 = "0.3"
